version: '3.8'
networks:
  devaten-dashboard-common-agent:
    name: devaten-dashboard-common-agent
    
services:

  devaten-activemq:
    image: rmohr/activemq:5.15.9
    container_name: devaten-activemq
    restart: unless-stopped
    # activemq username is devaten .you can find activemq password in onpremises-common-agent\Configurations\activemq\ACTIVEMQ_CONF\conf\jetty-realm.propeties file.
    # if you want to change password you can go above file location change it before run docker-compose.
    ports:
      - "8161:8161"
      - "61616:61616"
    networks:
      - devaten-dashboard-common-agent
    volumes:
      - ./Configurations/activemq/ACTIVEMQ_CONF/conf:/opt/activemq/conf:rw
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devaten@123
      MYSQL_DATABASE: devaten
    ports:
      - 0.0.0.0:3306:3306
    volumes:
      # Files 
      - ./mysql/my.cnf:/etc/alternatives/my.cnf
      # Dirs
      - ./mysql/datadir/:/var/lib/mysql:rw
      - "./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
    command:
      - --sql_mode=
      - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 30s
      timeout: 2s
      retries: 15
    networks:
      - devaten-dashboard-common-agent   
  
  devaten-dashboard-container:
    image: devaten/devaten-dashboard
    container_name: devaten-dashboard-container
    restart: always 
    environment:
      spring.datasource.username: root
      spring.datasource.password: devaten@123
      spring.flyway.user: root
      spring.flyway.password: devaten@123
      openai.apiKey: Enter-your-openai-key
      smtp.host: blade13.euronic.fi
      smtp.email: admin@devaten.com
      smtp.password: 47eyRnNFv69caaG
      smtp.port: 465
    depends_on: 
      mysqldb: 
        condition: service_healthy
    ports:
      - 8081:8081
    healthcheck:
      test: curl --fail http://localhost:8081 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s  
    networks:
      - devaten-dashboard-common-agent
   
  onpremise-commonagent-container:
    image: devaten/devaten-agent
    container_name: onpremise-commonagent-container
    restart: always
    depends_on: 
      devaten-dashboard-container: 
        condition: service_healthy
    ports:
      - "8111:8111"
    volumes:
      - ./Configurations/h2/:/Configurations/h2/:rw
      - ./Configurations/.devaten/.data:/Configurations/.devaten/.data:rw
    networks:
      - devaten-dashboard-common-agent   

volumes:
  h2-data: {}
